### ISSUE TITLE
Establishing connection on a host where there is already a fingerprint recorded generates a SIGSEGV

### ISSUE THREAD

**Issue by lstep** [mkishere/sshsyrup#5]
Establishing connection on a host where there is already a fingerprint recorded on the client generates a SIGSEGV

Trace : 

```bash
# ./sshsyrup
INFO[0020] Connection established                        srcIP="1.2.3.4:42246"
ERRO[0020] Error establishing SSH connection             error=EOF srcIP="1.2.3.4:42246"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x68e61a]

goroutine 38 [running]:
main.(*SSHSession).handleNewConn(0x0)
	/go/src/github.com/mkishere/sshsyrup/cmd/syrup/ssh.go:198 +0x3a
main.createSessionHandler(0xc420a1b9e0, 0xc4208b0000)
	/go/src/github.com/mkishere/sshsyrup/cmd/syrup/ssh.go:230 +0x4c
created by main.main
	/go/src/github.com/mkishere/sshsyrup/cmd/syrup/main.go:173 +0x25d
```

**Comment by victpork** [comment]
Hi @lstep,

May I know which version/commit you're working with? Can you confirm if the master tip has the same issue?

**Comment by victpork** [comment]
Now the connection will be closed gracefully instead of crashing the whole honeypot server

**Comment by lstep** [comment]
Yes, I took the latest  version (source master)
