### ISSUE TITLE
wget command doesn't take into account possiblity of not putting any argument

### ISSUE THREAD

**Issue by lstep** [mkishere/sshsyrup#6]
When an "intruder" types just `wget`, sshsyrup crashes : 

```
INFO[0095] User input command wget                       clientStr="SSH-2.0-OpenSSH_7.5p1 Ubuntu-10ubuntu0.1" cmd=wget sessionId="T3RoHBUHBUiQeJNwKO/FhhbOrV+w+yK1YsJn0NY=" srcIP="1.2.3.4:22670" user=root
panic: runtime error: index out of range

goroutine 81 [running]:
github.com/mkishere/sshsyrup/os/command.wget.Exec(0xc420d72f10, 0x0, 0x1, 0xc420b8d810, 0x0)
	/home/lstep/go/src/github.com/mkishere/sshsyrup/os/command/wget.go:39 +0x552
github.com/mkishere/sshsyrup/os/command.(*wget).Exec(0x912aa8, 0xc420d72f10, 0x0, 0x1, 0xc420b8d810, 0x1)
	<autogenerated>:1 +0x5c
github.com/mkishere/sshsyrup/os.(*Shell).Exec(0xc420d72c20, 0xc420d65360, 0x4, 0xc420d72f10, 0x0, 0x1, 0x1, 0x2, 0xc4200be780)
	/go/src/github.com/mkishere/sshsyrup/os/shell.go:107 +0xa0
github.com/mkishere/sshsyrup/os.(*Shell).HandleRequest(0xc420d72c20)
	/go/src/github.com/mkishere/sshsyrup/os/shell.go:83 +0x448
created by main.(*SSHSession).handleNewSession.func1
	/go/src/github.com/mkishere/sshsyrup/cmd/syrup/ssh.go:158 +0x1271
```

**Comment by victpork** [comment]
I still haven't got time to complete this yet - will resume the work on command once I finish/satisfy what I have done on sftp subsystem
